In [52]:
# import libraries
import pandas as pd
import matplotlib.pyplot as plt
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\bonit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

### Data Cleaning

In [53]:
survey = pd.read_csv("data/survey.csv")
survey.head()

,Timestamp,Rating,1st Favorite,2nd Favorite,3rd Favorite,Additional Feedback,Advertising Source,Residential Commons,Duration of Stay,Food or Activity Recommendations,PC Familiarity
0,2/13/2025 15:19:17,10,Pasta,Hot Chocolate,Photo Ops,NaN,Friends,Loyd,15 - 30 minutes,Pasta again,1
1,2/13/2025 15:19:30,10,Photo Ops,Bracelet Making,Hot Chocolate,NaN,Instagram,Loyd,15 - 30 minutes,NaN,4
2,2/13/2025 15:19:39,10,Hot Chocolate,Cupcakes,Pasta,NaN,Friends,Loyd,30 minutes - 1 hour,NaN,10
3,2/13/2025 15:23:57,10,Bouquets,Hot Chocolate,Bracelet Making,NaN,Friends,VS,30 minutes - 1 hour,More hangouts,7
4,2/13/2025 15:24:18,9,Bouquets,Hot Chocolate,Cupcakes,NaN,Instagram,VS,15 - 30 minutes,Decorating games,5

In [54]:
# remove extra spaces
survey["Food or Activity Recommendations"] = survey["Food or Activity Recommendations"].str.replace(r'\s+', ' ', regex=True).str.strip()

# lower case
survey["Food or Activity Recommendations"] = survey["Food or Activity Recommendations"].str.lower()

# remove special chars
survey["Food or Activity Recommendations"] = survey["Food or Activity Recommendations"].str.replace(
    r"[^a-zA-Z\s]", "", regex=True
)

# remove stop words
stopWords = set(stopwords.words("english"))
survey["Food or Activity Recommendations"] = survey["Food or Activity Recommendations"].apply(
    lambda x: ' '.join([word for word in str(x).split() if word.lower() not in stopWords]) if pd.notna(x) else x
)

survey.head()

,Timestamp,Rating,1st Favorite,2nd Favorite,3rd Favorite,Additional Feedback,Advertising Source,Residential Commons,Duration of Stay,Food or Activity Recommendations,PC Familiarity
0,2/13/2025 15:19:17,10,Pasta,Hot Chocolate,Photo Ops,NaN,Friends,Loyd,15 - 30 minutes,pasta,1
1,2/13/2025 15:19:30,10,Photo Ops,Bracelet Making,Hot Chocolate,NaN,Instagram,Loyd,15 - 30 minutes,NaN,4
2,2/13/2025 15:19:39,10,Hot Chocolate,Cupcakes,Pasta,NaN,Friends,Loyd,30 minutes - 1 hour,NaN,10
3,2/13/2025 15:23:57,10,Bouquets,Hot Chocolate,Bracelet Making,NaN,Friends,VS,30 minutes - 1 hour,hangouts,7
4,2/13/2025 15:24:18,9,Bouquets,Hot Chocolate,Cupcakes,NaN,Instagram,VS,15 - 30 minutes,decorating games,5

### Event Aspect Popularity

In [55]:
points = {"1st Favorite": 3, "2nd Favorite": 2, "3rd Favorite": 1}
aspect_scores = {}
favorites = survey[["1st Favorite", "2nd Favorite", "3rd Favorite"]]

for col in favorites.columns:
    for choice in favorites[col]:
        if choice not in aspect_scores:
            aspect_scores[choice] = 0
        aspect_scores[choice] += points[col]

sorted_scores = pd.DataFrame(aspect_scores.items(), columns=['Aspect', 'Total Points'])
sorted_scores = sorted_scores.sort_values(by='Total Points', ascending=False)
sorted_scores = sorted_scores.reset_index(drop=True)
sorted_scores

            Aspect  Total Points
0         Bouquets           122
1         Cupcakes            48
2    Hot Chocolate            40
3        Photo Ops            29
4            Pasta            24
5  Bracelet Making            14
6  Canvas Painting            10
7   Spinning Wheel             1

In [ ]:
costs = {
    "Bouquets": 5000,
    "Cupcakes": 650,
    "Hot Chocolate": 575,
    "Photo Ops": 1105,
    "Pasta": 1686.85
}

quantities = {
    "Bouquets": 300,
    "Cupcakes": 300,
    "Hot Chocolate": 300,
    "Pasta": 300
}